// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/sso/sso.proto

package go_micro_srv_sso

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_e469c66b548f3917, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

type AuthRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e469c66b548f3917, []int{1}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Expire               int64    `protobuf:"varint,2,opt,name=expire,proto3" json:"expire,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e469c66b548f3917, []int{2}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AuthResponse) GetExpire() int64 {
	if m != nil {
		return m.Expire
	}
	return 0
}

type RegisterRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	CaptchaId            string   `protobuf:"bytes,3,opt,name=captchaId,proto3" json:"captchaId,omitempty"`
	Verify               string   `protobuf:"bytes,4,opt,name=verify,proto3" json:"verify,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e469c66b548f3917, []int{3}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterRequest) GetCaptchaId() string {
	if m != nil {
		return m.CaptchaId
	}
	return ""
}

func (m *RegisterRequest) GetVerify() string {
	if m != nil {
		return m.Verify
	}
	return ""
}

type RegisterResponse struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Status               int64    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e469c66b548f3917, []int{4}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

type CaptchaRequest struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Length               int64    `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CaptchaRequest) Reset()         { *m = CaptchaRequest{} }
func (m *CaptchaRequest) String() string { return proto.CompactTextString(m) }
func (*CaptchaRequest) ProtoMessage()    {}
func (*CaptchaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e469c66b548f3917, []int{5}
}

func (m *CaptchaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CaptchaRequest.Unmarshal(m, b)
}
func (m *CaptchaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CaptchaRequest.Marshal(b, m, deterministic)
}
func (m *CaptchaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CaptchaRequest.Merge(m, src)
}
func (m *CaptchaRequest) XXX_Size() int {
	return xxx_messageInfo_CaptchaRequest.Size(m)
}
func (m *CaptchaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CaptchaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CaptchaRequest proto.InternalMessageInfo

func (m *CaptchaRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CaptchaRequest) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

type CaptchaResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CaptchaResponse) Reset()         { *m = CaptchaResponse{} }
func (m *CaptchaResponse) String() string { return proto.CompactTextString(m) }
func (*CaptchaResponse) ProtoMessage()    {}
func (*CaptchaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e469c66b548f3917, []int{6}
}

func (m *CaptchaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CaptchaResponse.Unmarshal(m, b)
}
func (m *CaptchaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CaptchaResponse.Marshal(b, m, deterministic)
}
func (m *CaptchaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CaptchaResponse.Merge(m, src)
}
func (m *CaptchaResponse) XXX_Size() int {
	return xxx_messageInfo_CaptchaResponse.Size(m)
}
func (m *CaptchaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CaptchaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CaptchaResponse proto.InternalMessageInfo

func (m *CaptchaResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CaptchaResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type StreamingRequest struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingRequest) Reset()         { *m = StreamingRequest{} }
func (m *StreamingRequest) String() string { return proto.CompactTextString(m) }
func (*StreamingRequest) ProtoMessage()    {}
func (*StreamingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e469c66b548f3917, []int{7}
}

func (m *StreamingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingRequest.Unmarshal(m, b)
}
func (m *StreamingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingRequest.Marshal(b, m, deterministic)
}
func (m *StreamingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingRequest.Merge(m, src)
}
func (m *StreamingRequest) XXX_Size() int {
	return xxx_messageInfo_StreamingRequest.Size(m)
}
func (m *StreamingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingRequest proto.InternalMessageInfo

func (m *StreamingRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type StreamingResponse struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingResponse) Reset()         { *m = StreamingResponse{} }
func (m *StreamingResponse) String() string { return proto.CompactTextString(m) }
func (*StreamingResponse) ProtoMessage()    {}
func (*StreamingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e469c66b548f3917, []int{8}
}

func (m *StreamingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingResponse.Unmarshal(m, b)
}
func (m *StreamingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingResponse.Marshal(b, m, deterministic)
}
func (m *StreamingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingResponse.Merge(m, src)
}
func (m *StreamingResponse) XXX_Size() int {
	return xxx_messageInfo_StreamingResponse.Size(m)
}
func (m *StreamingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingResponse proto.InternalMessageInfo

func (m *StreamingResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Ping struct {
	Stroke               int64    `protobuf:"varint,1,opt,name=stroke,proto3" json:"stroke,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_e469c66b548f3917, []int{9}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetStroke() int64 {
	if m != nil {
		return m.Stroke
	}
	return 0
}

type Pong struct {
	Stroke               int64    `protobuf:"varint,1,opt,name=stroke,proto3" json:"stroke,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_e469c66b548f3917, []int{10}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetStroke() int64 {
	if m != nil {
		return m.Stroke
	}
	return 0
}

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.srv.sso.Message")
	proto.RegisterType((*AuthRequest)(nil), "go.micro.srv.sso.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "go.micro.srv.sso.AuthResponse")
	proto.RegisterType((*RegisterRequest)(nil), "go.micro.srv.sso.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "go.micro.srv.sso.RegisterResponse")
	proto.RegisterType((*CaptchaRequest)(nil), "go.micro.srv.sso.CaptchaRequest")
	proto.RegisterType((*CaptchaResponse)(nil), "go.micro.srv.sso.CaptchaResponse")
	proto.RegisterType((*StreamingRequest)(nil), "go.micro.srv.sso.StreamingRequest")
	proto.RegisterType((*StreamingResponse)(nil), "go.micro.srv.sso.StreamingResponse")
	proto.RegisterType((*Ping)(nil), "go.micro.srv.sso.Ping")
	proto.RegisterType((*Pong)(nil), "go.micro.srv.sso.Pong")
}

func init() { proto.RegisterFile("proto/sso/sso.proto", fileDescriptor_e469c66b548f3917) }

var fileDescriptor_e469c66b548f3917 = []byte{
	// 449 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x4d, 0x6f, 0x13, 0x31,
	0x10, 0xed, 0x66, 0x93, 0x34, 0x1d, 0x50, 0x1b, 0x4c, 0x55, 0x45, 0x0b, 0x54, 0xad, 0xb9, 0x84,
	0xcb, 0x52, 0x81, 0xb8, 0xf5, 0x00, 0x42, 0x20, 0x38, 0x20, 0x55, 0x1b, 0xf8, 0x01, 0x26, 0x3b,
	0x6c, 0xac, 0x12, 0x7b, 0xf1, 0x78, 0x0b, 0x39, 0xf1, 0x13, 0xf8, 0xcb, 0x68, 0xfd, 0x91, 0x94,
	0x24, 0xcd, 0x85, 0xc3, 0x4a, 0x7e, 0x7e, 0xf3, 0x9e, 0xdf, 0x78, 0xac, 0x85, 0x87, 0xb5, 0xd1,
	0x56, 0x3f, 0x27, 0x72, 0x5f, 0xee, 0x10, 0x1b, 0x56, 0x3a, 0x9f, 0xcb, 0xa9, 0xd1, 0x39, 0x99,
	0x9b, 0x9c, 0x48, 0xf3, 0x47, 0xb0, 0xff, 0x09, 0x89, 0x44, 0x85, 0x6c, 0x08, 0x29, 0x89, 0xc5,
	0x28, 0x39, 0x4b, 0xc6, 0x07, 0x45, 0xbb, 0xe4, 0xef, 0xe0, 0xde, 0x9b, 0xc6, 0xce, 0x0a, 0xfc,
	0xd1, 0x20, 0x59, 0x96, 0xc1, 0xa0, 0x21, 0x34, 0x4a, 0xcc, 0x31, 0x54, 0x2d, 0x71, 0xcb, 0xd5,
	0x82, 0xe8, 0xa7, 0x36, 0xe5, 0xa8, 0xe3, 0xb9, 0x88, 0xf9, 0x25, 0xdc, 0xf7, 0x36, 0x54, 0x6b,
	0x45, 0xc8, 0x8e, 0xa1, 0x67, 0xf5, 0x35, 0xaa, 0x60, 0xe2, 0x01, 0x3b, 0x81, 0x3e, 0xfe, 0xaa,
	0xa5, 0x41, 0xa7, 0x4f, 0x8b, 0x80, 0xf8, 0x6f, 0x38, 0x2a, 0xb0, 0x92, 0x64, 0xd1, 0xfc, 0x67,
	0x10, 0xf6, 0x18, 0x0e, 0xa6, 0xa2, 0xb6, 0xd3, 0x99, 0xf8, 0x58, 0x8e, 0x52, 0x47, 0xae, 0x36,
	0xda, 0x00, 0x37, 0x68, 0xe4, 0xb7, 0xc5, 0xa8, 0xeb, 0xa8, 0x80, 0xf8, 0x7b, 0x18, 0xae, 0x02,
	0x84, 0x16, 0x76, 0x25, 0x38, 0x81, 0x3e, 0x59, 0x61, 0x1b, 0x8a, 0x8d, 0x78, 0xc4, 0x2f, 0xe1,
	0xf0, 0xad, 0x3f, 0x2c, 0xf6, 0xc1, 0xa0, 0x6b, 0x17, 0x75, 0x74, 0x70, 0xeb, 0x56, 0xfd, 0x1d,
	0x55, 0x65, 0x67, 0x51, 0xed, 0x11, 0x7f, 0x05, 0x47, 0x4b, 0x75, 0x08, 0x71, 0x08, 0x1d, 0x59,
	0x06, 0x71, 0x47, 0x96, 0xad, 0x5d, 0x29, 0xac, 0x08, 0x6d, 0xbb, 0x35, 0x1f, 0xc3, 0x70, 0x62,
	0x0d, 0x8a, 0xb9, 0x54, 0x55, 0x3c, 0xf6, 0x18, 0x7a, 0x53, 0xdd, 0x28, 0xeb, 0xa4, 0x69, 0xe1,
	0x01, 0x7f, 0x06, 0x0f, 0x6e, 0x55, 0xae, 0x46, 0xb5, 0xa5, 0xf4, 0x14, 0xba, 0x57, 0x52, 0x55,
	0xbe, 0x53, 0xa3, 0xaf, 0x31, 0xd0, 0x01, 0x39, 0x5e, 0xdf, 0xcd, 0xbf, 0xf8, 0x93, 0x42, 0x3a,
	0x21, 0xcd, 0x3e, 0x40, 0xef, 0xb3, 0x9b, 0xfd, 0x93, 0x7c, 0xfd, 0x61, 0xe6, 0xb7, 0x1e, 0x5e,
	0x76, 0x7a, 0x17, 0xed, 0x53, 0xf2, 0x3d, 0x36, 0x81, 0x41, 0x9c, 0x11, 0x3b, 0xdf, 0xac, 0x5e,
	0x7b, 0x40, 0x19, 0xdf, 0x55, 0xb2, 0x34, 0xbd, 0x82, 0xfd, 0x70, 0xe5, 0xec, 0x6c, 0x53, 0xf0,
	0xef, 0x2c, 0xb3, 0xf3, 0x1d, 0x15, 0x4b, 0xc7, 0x2f, 0xd0, 0xf7, 0x77, 0xcc, 0xb6, 0x24, 0x58,
	0x9f, 0x53, 0xf6, 0x74, 0x67, 0x4d, 0x34, 0xbd, 0x48, 0xd8, 0x6b, 0x18, 0xb4, 0xf3, 0xf0, 0x77,
	0xbe, 0x29, 0x6a, 0xb9, 0x6c, 0xdb, 0xbe, 0x56, 0x15, 0xdf, 0x1b, 0x27, 0x17, 0xc9, 0xd7, 0xbe,
	0xfb, 0x3f, 0xbc, 0xfc, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x6b, 0xc4, 0x0b, 0x2d, 0x36, 0x04, 0x00,
	0x00,
}
